export const headCells = [
  { id: 'image_url', numeric: false, disablePadding: false, label: 'Ảnh', maxWidth: 50 },
  { id: 'fullname', numeric: false, disablePadding: false, label: 'Khách hàng', maxWidth: 150 },
  { id: 'title', numeric: false, disablePadding: false, label: 'Tiêu đề', maxWidth: 150 },
  { id: 'part_code', numeric: false, disablePadding: false, label: 'Mã phụ tùng', maxWidth: 150 },
  { id: 'product_code', numeric: false, disablePadding: false, label: 'Mã thành phẩm', maxWidth: 150 },
  { id: 'category_name', numeric: false, disablePadding: false, label: 'Danh mục', maxWidth: 150 },
  { id: 'customer_name', numeric: false, disablePadding: false, label: 'Khách hàng', maxWidth: 150 },
  { id: 'product_customer_code', numeric: false, disablePadding: false, label: 'Mã khách hàng', maxWidth: 150 },
  { id: 'no_piece_per_box', numeric: false, disablePadding: false, label: 'Số lượng', maxWidth: 150 },
  { id: 'productivity_per_worker', numeric: false, disablePadding: false, label: 'Năng suất', maxWidth: 150 },
  { id: 'order_date', numeric: false, disablePadding: false, label: 'Ngày đặt hàng', maxWidth: 150 },
  { id: 'expected_deliver_date', numeric: false, disablePadding: false, label: 'Ngày giao hàng', maxWidth: 150 },
  { id: 'department_name', numeric: false, disablePadding: false, label: 'Tên phòng ban', maxWidth: 150 },
  { id: 'department_parent', numeric: false, disablePadding: false, label: 'Trực thuộc phòng ban', maxWidth: 150 },
  { id: 'number_member', numeric: false, disablePadding: false, label: 'Số thành viên', maxWidth: 150 },
  { id: 'account_id', numeric: false, disablePadding: false, label: 'ID', maxWidth: 50 },
  { id: 'full_name', numeric: false, disablePadding: false, label: 'Tên', maxWidth: 150 },
  { id: 'email_address', numeric: false, disablePadding: false, label: 'Email', maxWidth: 100 },
  { id: 'description', numeric: false, disablePadding: false, label: 'Mô tả', maxWidth: 100 },
  { id: 'number_phone', numeric: false, disablePadding: false, label: 'SĐT', maxWidth: 100 },
  { id: 'amount', numeric: false, disablePadding: false, label: 'Số lượng', maxWidth: 100 },
  { id: 'role_template_name', numeric: false, disablePadding: false, label: 'Chức vụ', maxWidth: 100 },
  { id: 'apply_to_department_type', numeric: false, disablePadding: false, label: 'Các phòng ban', maxWidth: 100 },
  { id: 'approval_role', numeric: false, disablePadding: false, label: 'Vai trò phê duyệt', maxWidth: 100 },
  {
    id: 'visible_for_selection',
    numeric: false,
    disablePadding: false,
    label: 'Hiển thị trong danh sách chọn',
    maxWidth: 150,
  },
  { id: 'active', numeric: false, disablePadding: false, label: 'Hoạt động', maxWidth: 100 },
  { id: 'created_by', numeric: false, disablePadding: false, label: 'Người tạo', maxWidth: 100 },
  { id: 'created_date', numeric: false, disablePadding: false, label: 'Ngày tạo', maxWidth: 100 },
  { id: 'is_active', numeric: false, disablePadding: false, label: 'Hoạt động', maxWidth: 150 },
  { id: 'is_featured', numeric: false, disablePadding: false, label: 'Nổi bật', maxWidth: 150 },
  { id: 'order__title', numeric: false, disablePadding: false, label: 'Tên kế hoạch', maxWidth: 150 },
  { id: 'from__date', numeric: false, disablePadding: false, label: 'Ngày bắt đầu', maxWidth: 150 },
  { id: 'to__date', numeric: false, disablePadding: false, label: 'Ngày kết thúc', maxWidth: 150 },
  { id: 'status__display', numeric: false, disablePadding: false, label: 'Trạng thái', maxWidth: 150 },

  { id: 'menuButtons', numeric: false, disablePadding: false, label: '', maxWidth: 150 },
];
