export const headCells = [
  { id: 'image_url', numeric: false, disablePadding: false, label: 'Ảnh', maxWidth: 50 },
  { id: 'fullname', numeric: false, disablePadding: false, label: 'Khách hàng', maxWidth: 150 },
  { id: 'received_code', numeric: false, disablePadding: false, label: 'Mã phiếu', maxWidth: 150 },
  { id: 'order_code', numeric: false, disablePadding: false, label: 'Mã đơn hàng', maxWidth: 150 },
  { id: 'part_code', numeric: false, disablePadding: false, label: 'Mã vật tư', maxWidth: 150 },
  { id: 'product_code', numeric: false, disablePadding: false, label: 'Mã thành phẩm', maxWidth: 150 },
  { id: 'customer_code', numeric: false, disablePadding: false, label: 'Mã khách hàng', maxWidth: 150 },
  { id: 'supplier_code', numeric: false, disablePadding: false, label: 'Mã nhà cung cấp', maxWidth: 150 },
  { id: 'inventory_check_code', numeric: false, disablePadding: false, label: 'Mã kiểm kho', maxWidth: 150 },
  { id: 'title', numeric: false, disablePadding: false, label: 'Tiêu đề', maxWidth: 150 },
  { id: 'part_name', numeric: false, disablePadding: false, label: 'Tên vật tư', maxWidth: 150 },
  { id: 'product_name', numeric: false, disablePadding: false, label: 'Tên thành phẩm ', maxWidth: 150 },
  { id: 'customer_name', numeric: false, disablePadding: false, label: 'Tên khách hàng', maxWidth: 150 },
  { id: 'supplier_name', numeric: false, disablePadding: false, label: 'Tên nhà cung cấp', maxWidth: 150 },
  { id: 'category_name', numeric: false, disablePadding: false, label: 'Danh mục', maxWidth: 150 },
  { id: 'warehouse_name', numeric: false, disablePadding: false, label: 'Tên kho', maxWidth: 150 },
  { id: 'workshop_name', numeric: false, disablePadding: false, label: 'Tên xưởng', maxWidth: 150 },
  { id: 'province_name', numeric: false, disablePadding: false, label: 'Tỉnh', maxWidth: 150 },
  { id: 'product_customer_code', numeric: false, disablePadding: false, label: 'Mã TP khách hàng', maxWidth: 150 },
  { id: 'no_piece_per_box', numeric: false, disablePadding: false, label: 'Số lượng', maxWidth: 150 },
  { id: 'productivity_per_worker', numeric: false, disablePadding: false, label: 'Năng suất', maxWidth: 150 },
  { id: 'quantity_in_piece', numberic: false, disablePadding: false, label: 'Số lượng', maxWidth: 150 },
  { id: 'quantity_in_box', numberic: false, disablePadding: false, label: 'Số lượng', maxWidth: 150 },
  { id: 'broken_quantity_in_piece', numberic: false, disablePadding: false, label: 'SL hỏng', maxWidth: 150 },
  { id: 'order_date', numeric: false, disablePadding: false, label: 'Ngày đặt hàng', maxWidth: 150 },
  { id: 'received_date', numeric: false, disablePadding: false, label: 'Ngày nhận hàng', maxWidth: 150 },
  { id: 'inventory_check_date', numeric: false, disablePadding: false, label: 'Ngày kiểm kho', maxWidth: 150 },
  { id: 'expected_deliver_date', numeric: false, disablePadding: false, label: 'Ngày giao hàng', maxWidth: 150 },
  { id: 'department_name', numeric: false, disablePadding: false, label: 'Tên phòng ban', maxWidth: 150 },
  { id: 'department_parent', numeric: false, disablePadding: false, label: 'Trực thuộc phòng ban', maxWidth: 150 },
  { id: 'number_member', numeric: false, disablePadding: false, label: 'Số thành viên', maxWidth: 150 },
  { id: 'account_id', numeric: false, disablePadding: false, label: 'ID', maxWidth: 50 },
  { id: 'full_name', numeric: false, disablePadding: false, label: 'Tên', maxWidth: 100 },
  { id: 'email_address', numeric: false, disablePadding: false, label: 'Email', maxWidth: 100 },
  { id: 'description', numeric: false, disablePadding: false, label: 'Mô tả', maxWidth: 100 },
  { id: 'number_phone', numeric: false, disablePadding: false, label: 'SĐT', maxWidth: 100 },
  { id: 'amount', numeric: false, disablePadding: false, label: 'Số lượng', maxWidth: 100 },
  { id: 'role_template_name', numeric: false, disablePadding: false, label: 'Chức vụ', maxWidth: 100 },
  { id: 'apply_to_department_type', numeric: false, disablePadding: false, label: 'Các phòng ban', maxWidth: 100 },
  { id: 'approval_role', numeric: false, disablePadding: false, label: 'Vai trò phê duyệt', maxWidth: 100 },
  {
    id: 'visible_for_selection',
    numeric: false,
    disablePadding: false,
    label: 'Hiển thị trong danh sách chọn',
    maxWidth: 150,
  },
  { id: 'is_part_list_available', numeric: false, disablePadding: false, label: 'Thành phần', maxWidth: 100 },
  { id: 'active', numeric: false, disablePadding: false, label: 'Hoạt động', maxWidth: 100 },
  { id: 'type', numeric: false, disablePadding: false, label: 'Thể loại', maxWidth: 150 },
  { id: 'created_by', numeric: false, disablePadding: false, label: 'Người tạo', maxWidth: 100 },
  { id: 'created_date', numeric: false, disablePadding: false, label: 'Ngày tạo', maxWidth: 100 },
  { id: 'percent_production', numeric: false, disablePadding: false, label: '% đã SX', maxWidth: 100 },
  { id: 'percent_plan', numeric: false, disablePadding: false, label: '% đã lập KH', maxWidth: 100 },

  { id: 'order__title', numeric: false, disablePadding: false, label: 'Tên kế hoạch', maxWidth: 150 },
  { id: 'from__date', numeric: false, disablePadding: false, label: 'Ngày bắt đầu', maxWidth: 150 },
  { id: 'to__date', numeric: false, disablePadding: false, label: 'Ngày kết thúc', maxWidth: 150 },
  { id: 'status__display', numeric: false, disablePadding: false, label: 'Trạng thái', maxWidth: 150 },
  { id: 'order_title', numeric: false, disablePadding: false, label: 'Tên kế hoạch', maxWidth: 150 },
  { id: 'number_of_worker', numeric: false, disablePadding: false, label: 'Số người làm', maxWidth: 150 },
  { id: 'number_of_working_hour', numeric: false, disablePadding: false, label: 'Số giờ làm', maxWidth: 150 },
  { id: 'work_order_date_string', numeric: false, disablePadding: false, label: 'Ngày', maxWidth: 150 },
  { id: 'user_group_code', numeric: false, disablePadding: false, label: 'Mã group', maxWidth: 150 },
  { id: 'user_group_name', numeric: false, disablePadding: false, label: 'Tên group', maxWidth: 150 },
  { id: 'user_group_number_member', numeric: false, disablePadding: false, label: 'Số người', maxWidth: 150 },
  { id: 'user_group_number_item', numeric: false, disablePadding: false, label: 'Số chức năng', maxWidth: 100 },
  { id: 'is_active', numeric: false, disablePadding: false, label: 'Hoạt động', maxWidth: 150 },
  { id: 'is_featured', numeric: false, disablePadding: false, label: 'Nổi bật', maxWidth: 150 },
  { id: 'file_url', numeric: false, disablePadding: false, label: 'Tải xuống', maxWidth: 150 },
  { id: 'menuButtons', numeric: false, disablePadding: false, label: '', maxWidth: 50 },
];
